# Generated by Django 4.2.4 on 2023-09-02 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
                ('teacher', models.CharField(max_length=64, verbose_name='teacher')),
                ('content', models.TextField(choices=[('informatics lessons', 'informatika dersleri'), ('Web Developer lessons', 'Web Developer derlseri'), ('Electonics lessons', 'Elektonika dersleri'), ('Python lessons', 'Python dersleri')], verbose_name='content')),
                ('description', models.TextField(verbose_name='Info')),
                ('category', models.CharField(choices=[('object', 'Əyani'), ('online', 'Online')], max_length=60, null=True, verbose_name='Kateqoriya')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=70, verbose_name='email')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('wpphone', models.IntegerField(verbose_name='Wp Number')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('is taught', 'Tədris Olunur'), ("isn't taught", 'Tədris Olunmur'), ('will be taught', 'Tədris Olunacaq')], max_length=60, null=True, verbose_name='Hal Hazirda')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
        ),
    ]
