# Generated by Django 4.2.4 on 2023-09-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_order_price_remove_order_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(choices=[('informatics lessons', 'informatika dersleri'), ('Backend lessons', 'Backend derlseri'), ('Frontend lessons', 'Backend derlseri'), ('Fullstack lessons', 'Fullstack derlseri'), ('Electonics lessons', 'Elektonika dersleri'), ('Python lessons', 'Python dersleri')], verbose_name='content'),
        ),
    ]
