# Generated by Django 4.2.4 on 2023-09-11 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='teachers',
        ),
        migrations.AddField(
            model_name='product',
            name='teachers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacher'),
        ),
    ]
