# Generated by Django 4.2.4 on 2023-09-11 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_remove_order_teachers_product_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(choices=[('informatics lessons', 'informatika dersleri'), ('Backend lessons', 'Backend derlseri'), ('Frontend lessons', 'FrontEnd derlseri'), ('Fullstack lessons', 'Fullstack derlseri'), ('Electonics lessons', 'Elektonika dersleri'), ('Python lessons', 'Python dersleri')], verbose_name='content'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photo/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
