# Generated by Django 4.2.4 on 2023-09-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('qiyabi', 'Əyani'), ('online', 'Online')], max_length=60, null=True, verbose_name='Kateqoriya'),
        ),
    ]
